package hibernate;
// Generated 29-may-2015 21:18:46 by Hibernate Tools 4.3.1



/**
 * Amigo generated by hbm2java
 */
public class Amigo  implements java.io.Serializable {


     private Integer id;
     private String usuarioInvita;
     private String usuarioAcepta;

    public Amigo() {
    }

    public Amigo(String usuarioInvita, String usuarioAcepta) {
       this.usuarioInvita = usuarioInvita;
       this.usuarioAcepta = usuarioAcepta;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getUsuarioInvita() {
        return this.usuarioInvita;
    }
    
    public void setUsuarioInvita(String usuarioInvita) {
        this.usuarioInvita = usuarioInvita;
    }
    public String getUsuarioAcepta() {
        return this.usuarioAcepta;
    }
    
    public void setUsuarioAcepta(String usuarioAcepta) {
        this.usuarioAcepta = usuarioAcepta;
    }




}


