package hibernate;
// Generated 29-may-2015 21:18:46 by Hibernate Tools 4.3.1



/**
 * Localizacion generated by hbm2java
 */
public class Localizacion  implements java.io.Serializable {


     private Integer id;
     private String usuario;
     private String localizacion;

    public Localizacion() {
    }

    public Localizacion(String usuario, String localizacion) {
       this.usuario = usuario;
       this.localizacion = localizacion;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }
    public String getLocalizacion() {
        return this.localizacion;
    }
    
    public void setLocalizacion(String localizacion) {
        this.localizacion = localizacion;
    }




}


