package hibernate;
// Generated 29-may-2015 21:18:46 by Hibernate Tools 4.3.1



/**
 * Persona generated by hbm2java
 */
public class Persona  implements java.io.Serializable {


     private Integer id;
     private String nombre;
     private String apellidos;
     private String nombreUsuario;
     private String clave;
     private String foto;
     private String localizacion;

    public Persona() {
    }

	
    public Persona(String nombre, String apellidos, String nombreUsuario, String clave) {
        this.nombre = nombre;
        this.apellidos = apellidos;
        this.nombreUsuario = nombreUsuario;
        this.clave = clave;
    }
    public Persona(String nombre, String apellidos, String nombreUsuario, String clave, String foto, String localizacion) {
       this.nombre = nombre;
       this.apellidos = apellidos;
       this.nombreUsuario = nombreUsuario;
       this.clave = clave;
       this.foto = foto;
       this.localizacion = localizacion;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }
    public String getNombreUsuario() {
        return this.nombreUsuario;
    }
    
    public void setNombreUsuario(String nombreUsuario) {
        this.nombreUsuario = nombreUsuario;
    }
    public String getClave() {
        return this.clave;
    }
    
    public void setClave(String clave) {
        this.clave = clave;
    }
    public String getFoto() {
        return this.foto;
    }
    
    public void setFoto(String foto) {
        this.foto = foto;
    }
    public String getLocalizacion() {
        return this.localizacion;
    }
    
    public void setLocalizacion(String localizacion) {
        this.localizacion = localizacion;
    }




}


